- name: Deploy VMs
  hosts: localhost
  gather_facts: no

  ### in DNS we have fix defined rhvm100 - rhvm199 with ip 10.14.11.100- 10.14.11.199
  #vars:
  #  create_vms_num: 2
  #  create_vms_start: 100
  #
  ### This playbook relies on variables defined for each system type
  ### In Satellite the following host collections are created
  ### - hana
  ### - ocp
  ### - ceph  
  ###  each has a croressponding activtion key for  --org="Default_Organization" in Satellite
  ###
  ### The system type variable is used to read in the configuration of the VM, that will be
  ### if its undefined it will throw an error right here
  ### 
  ### create_vms_type: hana

  # Infos
  # Dswitch name: "GSCOE Dswitch"
  tasks:
     - name: Check if Vmtype is defined
       fail: 
         msg: "Please define VM type"
       when: create_vms_type is undefined
     - name: Check if start VM is defined
       fail: 
         msg: "Please define first VM"
       when: create_vms_start is undefined
     - name: Check if number of VMs is defined
       fail: 
         msg: "Please define how many VMs you want to create"
       when: create_vms_num is undefined

     - name: include system configuration
       include_vars: vmtypes/{{ create_vms_type }}.yml
 
     - name: Create a virtual machine from a template
       vmware_guest:
         #hostname: *** LOADED FROM TOWER CREDENTIAL ***
         #username: *** LOADED FROM TOWER CREDENTIAL ***
         #password: *** LOADED FROM TOWER CREDENTIAL ***
         validate_certs: False
         datacenter: "GSCOE Datacenter"
         cluster: "E7v4 Cluster"
         folder: "/GSCOE Datacenter/vm/RedHat Demos"
         name: rhvm{{ item }}
         state: poweredon
         template: "RHEL7.4-template" 
         #customization_spec: "rhel 7"
         customization:
           hostname: rhvm{{ item }}
           domain: gscoe.intern
         disk:
         - size_gb: "{{ vmtype_boot_disk }}"
           type: thin
           datastore: "RedHat Demos"
         - size_gb: "{{ vmtype_data_disk }}"
           type: thin
           datastore: "RedHat Demos"
         hardware:
           memory_mb: "{{ vmtype_mem_mb }}"
           num_cpus: "{{ vmtype_cpus }}"
         networks: 
           - name: "RedHat Demos 1411"
             ip: 10.14.11.{{ item }}
             netmask: 255.255.255.0
             gateway: 10.14.11.1 
             domain: gscoe.intern
             dns_servers: 
             - 172.16.17.3 
         wait_for_ip_address: true
       loop: "{{ range(create_vms_start, create_vms_start + create_vms_num, 1)| list }}"
       register: vm_creation

     - name: Ensure VM is added to a local group
       add_host:
          name: "{{ item.instance.ipv4 }}"
          groups: newvm
       with_items: "{{ vm_creation.results }}"

     - name: Debug hostgroup
       debug: var=groups

- name: Register new VMs to Satellite with activation key
  hosts: newvm

  vars:
    satellite_server: satellite.gscoe.intern
    reg_activation_key: "{{ create_vms_type }}"
    reg_organization_id: "Default_Organization"
    reg_server_insecure: yes
    reg_osrelease: 7.6
    repo_reset: false
    repositories:
      - rhel-7-server-eus-rpms
      - rhel-sap-hana-for-rhel-7-server-eus-rpms
      - rhel-7-server-eus-satellite-tools-6.4-rpms
      - rhel-7-server-eus-optional-rpms
    
  pre_tasks:
     - name: fix bugs for nameserver from vmware_guest module (DNS Server not set)
       block:
         - lineinfile:
             regexp: '^DNS1='
             path: /etc/sysconfig/network-scripts/ifcfg-eth0
             line: 'DNS1=172.16.17.3'
             insertafter: '^DOMAIN='
         - lineinfile:
             regexp: '^nameserver 172.16.17.3'
             path: /etc/resolv.conf
             line: 'nameserver 172.16.17.3'
             insertafter: '^search'
  roles:
      - mk-ansible-roles.subscribe-rhn

  tasks:
      - name: Install Satellite CLient
        yum:
           name: katello-agent
           state: present

