---

- file:
    name: /hana
    state: directory
    owner: root
    group: root

- file:
    name: /hana/data
    state: directory
    owner: root
    group: root

- file:
    name: /hana/log
    state: directory
    owner: root
    group: root

- file:
    name: /hana/shared
    state: directory
    owner: root
    group: root

- file:
    name: "{{  installroot }}"
    state: directory
    owner: root
    group: root

- name: install NFS packages for mounting
  yum: state=present name=nfs-utils
  
- name: mount installdir
  mount:
      src: "{{ install_nfs }}"
      name: /tmp/install
      fstype: nfs
      state: mounted
  when: not( (install_nfs is undefined) or (install_nfs is none) or (install_nfs | trim == '') )

- name: extract installer
  shell: cd {{ installroot }} && unrar x "/tmp/install/{{ installversion }}_part1.exe"
  
- name: mount installdir
  mount:
      src: "{{ install_nfs }}"
      name: /tmp/install
      fstype: nfs
      state: unmounted
  when: not( (install_nfs is undefined) or (install_nfs is none) or (install_nfs | trim == '') )

- name: Get HANA Version Information
  shell: |
    INSTDIR='{{ installroot }}'
    VERSION='{{ installversion }}'
    awk ' ( $1 == "fullversion:" ) { print $2}'  ${INSTDIR}/${VERSION}/DATA_UNITS/HDB_SERVER_LINUX_X86_64/server/manifest
  register: hanaversion

...
